language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python setup.py install
  - pip install nose coverage
script:
  - nosetests --nologcapture --cover-branches --with-coverage --cover-package=epeolatry
after_success:
  - pip install codecov && codecov